#
# Makefile for the memory technology device drivers.
#
# Core functionality.

ifeq ($(strip $(llt_gcov)),y)
GCOV_PROFILE := y
endif

obj-y				+= OmCommonPpm.o 
obj-y				+= OmHsicPpm.o 
obj-y				+= OmSocketPpm.o 
obj-y				+= OmUsbPpm.o 
obj-y				+= OmVcomPpm.o 



