# MD5: 999fd37dc31e1e1780fc7dc938207615
CFG_FEATURE_ON                                  := 1
CFG_FEATURE_OFF                                 := 0
CFG_FEATURE_ACPU_FC_POINT_REG                   := FEATURE_ON
CFG_FEATURE_ACPU_STAT                           := FEATURE_OFF
CFG_FEATURE_BBPMST_FREQUENCY_REDUCE             := FEATURE_OFF
CFG_FEATURE_CSD                                 := FEATURE_OFF
CFG_FEATURE_CST_ASYN_OR_NOT_TRANS               := FEATURE_OFF
CFG_FEATURE_HARDWARE_HDLC_FUNC                  := FEATURE_OFF
CFG_FEATURE_HISOCKET                            := FEATURE_OFF
CFG_FEATURE_MMU_MEDIUM                          := FEATURE_ON
CFG_FEATURE_NFEXT                               := FEATURE_ON
CFG_FEATURE_PPP                                 := FEATURE_ON
CFG_FEATURE_SMALL_MAILBOX                       := FEATURE_OFF
CFG_FEATURE_TTF_MEM_DEBUG                       := FEATURE_ON
CFG_FEATURE_VISP_VPP                            := FEATURE_ON
CFG_VISP_IMS_NIC_CNT                            := 8
CFG_TTF_MEM_POOL_CFG                            := TTF_MEM_SPECIFICATION3
CFG_TTF_CF_FEATURE                              := FEATURE_OFF
CFG_FEATURE_DSDS                                := FEATURE_ON
CFG_GAS_PTL_VER_PRE_R99                         := (PS_PTL_VER_PRE_R99)
CFG_GAS_PTL_VER_R99                             := (PS_PTL_VER_R99)
CFG_GAS_PTL_VER_R3                              := (PS_PTL_VER_R3)
CFG_GAS_PTL_VER_R4                              := (PS_PTL_VER_R4)
CFG_GAS_PTL_VER_R5                              := (PS_PTL_VER_R5)
CFG_GAS_PTL_VER_R6                              := (PS_PTL_VER_R6)
CFG_GAS_PTL_VER_R7                              := (PS_PTL_VER_R7)
CFG_GAS_PTL_VER_R8                              := (PS_PTL_VER_R8)
CFG_GAS_PTL_VER_R9                              := (PS_PTL_VER_R9)
CFG_GAS_UE_REL_VER                              := (GAS_PTL_VER_R9)
CFG_FEATURE_DC_MIMO                             := FEATURE_OFF
CFG_FEATURE_DC_UPA                              := FEATURE_OFF
CFG_FEATURE_DL_E_CELL_FACH                      := FEATURE_ON
CFG_FEATURE_UL_E_CELL_FACH                      := FEATURE_ON
CFG_FEATURE_MODEM1_SUPPORT_WCDMA                := FEATURE_ON
CFG_FEATURE_HARDWARE_HDLC_ON_CCPU               := FEATURE_ON
ifeq ($(cdma),false)
CFG_FEATURE_UE_MODE_CDMA                        := FEATURE_OFF
else
CFG_FEATURE_UE_MODE_CDMA                        := FEATURE_ON
endif
CFG_FEATURE_BASTET                              := FEATURE_ON
CFG_GU_PRODUCT_VERSION                          := VERSION_V7R1
