#
# Makefile for the memory technology device drivers.
#
# Core functionality.

ifeq ($(strip $(llt_gcov)),y)
GCOV_PROFILE := y
endif


obj-y				+= scm_ind_dst.o 
obj-y				+= scm_ind_src.o 
obj-y				+= scm_cnf_dst.o 
obj-y				+= scm_cnf_src.o 
obj-y				+= scm_common.o 
obj-y				+= scm_debug.o 
obj-y				+= scm_init.o 
obj-y				+= scm_cfg.o 


