# MD5: 6ab49915244441a2d4c187e2e83063e4
CFG_FEATURE_AT_NV_WRITE_SUPPORT                 := YES
CFG_FEATURE_READ_LOG_FILTER_CFG                 := YES
CFG_FEATURE_MEMCPY_REBOOT_CFG                   := FEATURE_ON
CFG_FEATURE_PHONE_ENG_AT_CMD                    := FEATURE_ON
